### ISSUE TITLE
Use JQ syntax for typed path and index.

### ISSUE THREAD

**Issue by ahoy-jon** [univalence/spark-tools#14]
before
```
a.b.c
d[1].e
f/h
i[last].j
```

after
```
.a.b.c
.d[0].e
.f[].h
.i[-1].j
```

We have also to make the syntax clearer :
for path `key".a[].b"`
for index `index".a[0].b"`

TODO : 
* Fix the parser, 
* Support the old syntax ".a.b" for ~path~ key
* Rename path in key
* Rename io.univalence.typedpath  in io.univalence.strings

* Fix the macro

**Comment by ahoy-jon** [comment]
We have also to make the syntax clearer : 
for path
```
key".a[].b"
```
for index
```
index".a[0].b"
```

**Comment by HarrisonCheng** [comment]
@ahoy-jon Quand tu as le temps tu pourras check ce qui a été fait ?

**Comment by ahoy-jon** [comment]
c'est bon pour moi, après il faudrait mettre à jour les macros ...
