### ISSUE TITLE
[spark-test] bug ! those two dataset should be equal.

### ISSUE THREAD

**Issue by ahoy-jon** [univalence/spark-tools#19]
in
 https://github.com/univalence/spark-tools/blob/52814a283ec346b2093af2ae9a4476c0125cde9d/spark-test/src/test/scala/io/univalence/sparktest/bug/DataFrameEqualityBugSparkTraining.scala

two datasets that are the same, should be equal!

**Comment by HarrisonCheng** [comment]
Fixed in https://github.com/univalence/spark-tools/commit/9ca72af77831d636a3306e31bc9ee8489d853695 and https://github.com/univalence/spark-tools/commit/6bb24921404d5723ce6f357842b7a60716dd54ea
