### ISSUE TITLE
[sparkTest] Generate Scala doc 

### ISSUE THREAD

**Issue by HarrisonCheng** [univalence/spark-tools#21]

**Comment by fsarradin** [comment]
Generate and publish Scaladoc.

* To generate : `sbt <project>/doc`
* To publish, we need to publish into Maven Central (Sonatype - OSSRH) so the doc might be captured by https://javadoc.io/

**Comment by fsarradin** [comment]
Nota : the tag `@configuration` in scaladoc isn't recognized. And it doesn't seem to be a way to define custom tags.

**Comment by HarrisonCheng** [comment]
On peut sync bintray avec maven central : https://reflectoring.io/bintray-jcenter-maven-central/

**Comment by HarrisonCheng** [comment]
Du coup même en publiant dans maven je ne retrouve pas la doc dans javadoc.io. Ils update peut-être à intervalle régulier. Une idée @fsarradin ?

**Comment by HarrisonCheng** [comment]
Nvm je viens de trouver : https://www.javadoc.io/doc/io.univalence/spark-test_2.11/0.2+347-ce741e3f
C'est top !

**Comment by fsarradin** [comment]
Il faut attendre 24h max pour une mise à jour dans javadoc.io
