### ISSUE TITLE
[parka] version conflict on cats

### ISSUE THREAD

**Issue by fsarradin** [univalence/spark-tools#24]
The current (and last) version of algebird needs cats 0.9.0 vs circe needs cats 1.5.0. This issue is emited by sbt.

~To solve this issue a solution would be to downgrade circe to 0.8.0.~

**Comment by ahoy-jon** [comment]
It's unfortunate. That being said, when we use algebird with cats 1.5.0, what happens?

I didn't witness a lot of cats usage in the lib.

**Comment by fsarradin** [comment]
=> Put an exclude of cats 0.9.0 while importing algebird.

**Comment by ahoy-jon** [comment]
I forced the exclusion on `org.typelevel`. It seems to be ok for now.

https://github.com/univalence/spark-tools/blob/33dadf5e429601883cf875cab2c0bf36f03d6f7e/build.sbt#L147-L150
